import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          .mySpan {
            color: red;
          }
        `}
      </style>
      <Head>
        <title>Atulya Hearing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo192.png" />
      </Head>
      <Script src="/web.js" strategy="lazyOnload"></Script>

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <Image
            className={styles.myImg}
            src="/logo512.png"
            width={237}
            height={158}
            alt="Atulya Hearing"
          />
        </div>
        <h1 className={styles.title}>
          <span className="dummy">&lt;Atulya Hearing &gt;</span>
        </h1>
        <div>
          <h4 className={styles.h2}>What can we do for your hearing loss?</h4>
          <div>
            <p>
              We partner with dealers that render exceptional hearing devices
              which are supplemented with enhanced hearing technology for a
              mesmerizing experience. Our hearing solutions are beneficial for
              the welfare of your health.!
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
